ministryofjustice/hmpps-dpr-data-product-definitions

src/test/kotlin/uk/gov/justice/digital/hmpps/dprdpdsservice/controller/integration/DefinitionsServiceIntegrationTest.kt
This change is to redeploy main to Dev as currently a branch is deployed for testing purposes.
=> DPR2-343 revert branch deployment to Dev

src/main/resources/definitions/prisons/orphanage/dpd001-hospital-movements.json
=> Hospital Movements dpd separated from courts

src/main/resources/definitions/prisons/disabled/dpd001-court-hospital-movements.json, src/main/resources/definitions/prisons/disabled/external-movements.json, src/main/resources/definitions/prisons/orphanage/dpd001-hospital-and-court-movements-1.0.4.json, src/main/resources/definitions/prisons/orphanage/dpd001-hospital-movements.json, src/main/resources/definitions/prisons/orphanage/external-movements.json, src/main/resources/definitions/prisons/test/test-report.json
Converted the "visible" report field from Boolean to Enum.
=> DPR2-413 visible from boolean to enum

src/main/resources/definitions/prisons/orphanage/external-movements.json
Data Product : External Movements : Set Mandatory fields
=> External Movements : Set Mandatory fields

src/main/resources/dev/definitions/prisons/test/external-movements-with-metrics.json, src/test/kotlin/uk/gov/justice/digital/hmpps/dprdpdsservice/controller/integration/DefinitionsServiceIntegrationTest.kt
Test DPD to test retrieving the metrics and dashboard definitions.
=> DPR2-1119 add test DPD for metrics

src/main/resources/dev/definitions/prisons/test/missing-ethnicity-metrics.json
Updated missing ethnicity DPD to reflect the new amended schema and also added the raw count of prisoners to the query.
=> DPR2-1220 updated missing ethnicity DPD with new amended definition

src/main/resources/dev/definitions/prisons/orphanage/ors-ual-records.json, src/main/resources/preprod/definitions/prisons/orphanage/ors-ual-records.json, src/main/resources/test/definitions/prisons/orphanage/ors-ual-records.json
Changed establishment name to establishment code to match what the prompt is capturing based on test feedback.
=> DPR2-1231 test feedback - change establishment name to code

src/main/resources/dev/definitions/prisons/orphanage/ors-security-movements.json, src/main/resources/preprod/definitions/prisons/orphanage/ors-security-movements.json, src/main/resources/test/definitions/prisons/orphanage/ors-security-movements.json
- **ORS Security Movements** format date
=> DPR2-1233 ors-security-movements format date

src/main/resources/dev/definitions/prisons/orphanage/ors-ual-records.json, src/main/resources/preprod/definitions/prisons/orphanage/ors-ual-records.json, src/main/resources/test/definitions/prisons/orphanage/ors-ual-records.json
Format date based on test feedback.
=> DPR2-1231 format date

src/main/resources/dev/definitions/prisons/orphanage/ors-transfers-in-and-out-of-establishments.json, src/main/resources/preprod/definitions/prisons/orphanage/ors-transfers-in-and-out-of-establishments.json, src/main/resources/test/definitions/prisons/orphanage/ors-transfers-in-and-out-of-establishments.json
Fixed time format for transfers_in_and_out_of_establisments
=> DPR2-1231 fix time format

src/main/resources/dev/definitions/prisons/orphanage/ors-view-diary-for-a-day.json, src/main/resources/preprod/definitions/prisons/orphanage/ors-view-diary-for-a-day.json, src/main/resources/test/definitions/prisons/orphanage/ors-view-diary-for-a-day.json
Removed V_RELEASEDESTINATION column from releases report as it's not needed (confirmed with Caroline).
=> DPR2-1231 removed V_RELEASEDESTINATION column from releases report

src/main/resources/dev/definitions/prisons/orphanage/national-social-visit-report.json, src/main/resources/preprod/definitions/prisons/orphanage/national-social-visit-report.json, src/main/resources/test/definitions/prisons/orphanage/national-social-visit-report.json
National social visits default sort on ESTABLISHMENT_DESCRIPTION
=> Dpr2 1060 national social visits

src/main/resources/dev/definitions/prisons/orphanage/ors-prisoners-without-visit-history.json, src/main/resources/preprod/definitions/prisons/orphanage/ors-prisoners-without-visit-history.json, src/main/resources/test/definitions/prisons/orphanage/ors-prisoners-without-visit-history.json
Prisoners without visit history default sort on NOMS Number.
=> DPR2-1172 prisoners without visit history default sort on NOMS Number

src/main/resources/dev/definitions/prisons/orphanage/ors-alternative-unlock-list.json, src/main/resources/preprod/definitions/prisons/orphanage/ors-alternative-unlock-list.json, src/main/resources/test/definitions/prisons/orphanage/ors-alternative-unlock-list.json
**- ORS Alternative Unlock List**  column tweaks, reorder
=> [DPR2-1233] ORS Alternative Unlock List - column tweaks

src/main/resources/dev/definitions/prisons/orphanage/ors-alternative-unlock-list.json, src/main/resources/preprod/definitions/prisons/orphanage/ors-alternative-unlock-list.json, src/main/resources/test/definitions/prisons/orphanage/ors-alternative-unlock-list.json
**- ORS Alternative Unlock List** column renames
=> [DPR2-1233] column renames

src/main/resources/dev/definitions/prisons/test/missing-ethnicity-metrics.json
Update test metrics definition.
=> DPR2-1439 update metrics definition

.github/workflows/publish.yml
Adds a tag to each merge to main, to help track releases and rollbacks.
=> [DPR2-1514] Tagging

dpd/dev/definitions/prisons/orphanage/data-quality-metrics-filters-testing.json, dpd/preprod/definitions/prisons/orphanage/data-quality-metrics-filters-testing.json, dpd/test/definitions/prisons/orphanage/data-quality-metrics-filters-testing.json
Updated dashboard definitions based on latest FE changes.
=> DPR2-1740 update dashboard definitions

dpd/test/definitions/prisons/probation/oasys-probation-at-court.json, dpd/test/definitions/prisons/probation/onr-probation-assessment.json, dpd/test/definitions/prisons/probation/onr-probation-multi-reports.json
Created DPD for OASYS and ONR connectivity probation poc
=> PDD-7-poc-connectivity-test

dpd/test/definitions/prisons/probation/dashboard-probation-report.json, dpd/test/definitions/prisons/probation/simple-dashboard-probation-report.json
Added all type dashboard sample probation for ONR
=> PDD-8-poc-dashboard-dpd-creation

dpd/dev/definitions/prisons/clean/ors-prisoner-iep-levels.json
Partially amended ORS Prisoner IEP Levels report.
=> DPR2-1952 amend ORS Prisoner IEP Levels report

dpd/dev/definitions/prisons/clean/ors-prisoner-iep-levels.json
Add distinct count as a section header and total row count per section as section footer.
=> DPR2-1952 by location - add as distinct as count section header and total count as footer

dpd/dev/definitions/prisons/orphanage/ors-prisoners-missing-pnc-number.json
added V_CASE_ADMINISTRATOR cte
added total
added default sort, renamed col to cell
=> DPR2-1949 updated ors-prisoners-missing-pnc-number

dpd/dev/definitions/prisons/orphanage/ors-convicted-prisoners-missing-cro-number.json
added CTE for V_CASE_ADMINISTRATOR
added total
=> DPR2-1951 update ors-convicted-prisoners-missing-cro-number

dpd/dev/definitions/prisons/clean/ors-prisoner-iep-levels.json
Fixes for the following reports:
- by IEP Level and IEP Date
- by NOMS Number
- by Nationality
- by Prisoner
=> DPR2-1952 fixes to more reports

dpd/dev/definitions/prisons/clean/ors-prisoner-iep-levels.json
These changes fix the following reports:
- By Legal status and IEP Level
- Simple By Last Name
- Simple By Location
- Summary
=> DPR2-1952 further fixes

dpd/dev/definitions/prisons/clean/ors-prisoner-iep-levels.json
Change the report template to summary from list to remove empty rows and pagination.
=> DPR2-1952 fix summary report

dpd/test/definitions/prisons/probation/dashboard-probation-report.json, dpd/test/definitions/prisons/probation/ndelius-probation-assessment.json, dpd/test/definitions/prisons/probation/simple-dashboard-probation-report.json
Some corrections to existing DPDs and Added Ndelius DPD
=> PDD-9-poc-ndelius-dpd-creation

dpd/dev/definitions/prisons/probation/ndmis-probation-offender.json, dpd/test/definitions/prisons/probation/dashboard-probation-report.json, dpd/test/definitions/prisons/probation/ndelius-probation-assessment.json, dpd/test/definitions/prisons/probation/simple-dashboard-probation-report.json
- Added Ndmis probation report for offender
- Some clean up on Probation dashboard report
=> Pdd 9 poc ndelius dpd creation

dpd/dev/definitions/prisons/clean/ors-irc-spends.json
Reverts ministryofjustice/hmpps-dpr-data-product-definitions#378
=> Revert "update ors irc spends to use formula and move to orphanage"
